apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-server
provisioner: kubernetes.io/NFS-server
parameters:
  server: 10.10.10.112
  path: /srv/nfs4/mysql-volume
  readOnly: "false"